### ISSUE TITLE
Purpose of the driver

### ISSUE THREAD

**Issue by wenq1** [openstf/node-minicap#1]
Hi guys,

Is the driver intended to manipulate JPEG frames received from the devices?  I already see an example app.js in the minicap repo. Does this driver serve its enhanced purpose?

**Comment by sorccu** [comment]
You can use it if you want but it's not very good, it's only a minimal example after all. It will work, though. We have a better one over at [openstf/node-minicap](https://github.com/openstf/node-minicap) which you can see in use [here](https://github.com/openstf/ios-minicap/blob/master/example/app.js).
